# Generated by Django 6.0.4 on 2026-04-29 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон повинен бути у форматі +XXXXXXXXXXX', regex='^\\+?\\d{10,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delivery_type', models.CharField(choices=[('nova', 'Нова Пошта'), ('ukr', 'Укрпошта')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('payment_type', models.CharField(choices=[('card', 'Карткою онлайн'), ('cash', 'При отриманні')], max_length=10)),
                ('total', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', '🆕 Нове'), ('processing', '⚙️ В обробці'), ('shipped', '📦 Відправлено'), ('done', '✅ Виконано')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(default='Без кольору', max_length=50)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Товар у замовленні',
                'verbose_name_plural': 'Товари у замовленні',
            },
        ),
    ]
