# Generated by Django 6.0.4 on 2026-06-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_options_remove_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика продажів',
                'verbose_name_plural': '📊 Статистика продажів',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
