# Generated by Django 6.0.4 on 2026-06-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_salesdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Замовлень')),
                ('total_spent', models.PositiveIntegerField(default=0, verbose_name='Витрачено ₴')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Перше замовлення')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='Останнє замовлення')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ['-last_order_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customer', verbose_name='Клієнт'),
        ),
    ]
