# Generated by Django 6.0.4 on 2026-04-29 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('emoji', models.CharField(default='👔', max_length=10, verbose_name='Emoji')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стара ціна')),
                ('description', models.TextField(verbose_name='Опис')),
                ('emoji', models.CharField(default='👔', max_length=10, verbose_name='Emoji (fallback без фото)')),
                ('sizes', models.JSONField(default=list, verbose_name='Розміри')),
                ('details', models.JSONField(blank=True, default=dict, help_text='{"Склад":"...", "Країна":"...", "Колір":"..."}', verbose_name='Деталі')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='Бейдж')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наявності')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок (0 = головне)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
                'ordering': ['order'],
            },
        ),
    ]
