# Generated by Django 6.0.4 on 2026-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ціна закупки'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість на складі'),
        ),
    ]
