# Generated by Django 6.0.4 on 2026-06-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_in_stock_product_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Розмір')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Залишок по розміру',
                'verbose_name_plural': 'Залишки по розмірах',
                'ordering': ['size'],
                'unique_together': {('product', 'size')},
            },
        ),
    ]
