# Generated by Django 6.0.4 on 2026-06-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsizestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='external_url',
            field=models.URLField(blank=True, default='', verbose_name='URL фото (зовнішнє)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Фото'),
        ),
    ]
